PruebaCECROPIACinthya/PruebaCECROPIACinthya/Models/Patient.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace PruebaCECROPIACinthya.Models
{
    //[Table("PatientTB")]
    public class Patient
    {
        [Required(ErrorMessage = "Enter First Name")]
        public string FirstName { get; set; }
        [Required(ErrorMessage = "Enter Last Name")]
        public string LastName { get; set; }
        [Key]
		public string ID { get; set; }
		public Nullable<System.DateTime> DateBirth { get; set; }
		public Nullable<int> Nationality { get; set; }
		public string Diseases { get; set; }
		public string PhoneNumber { get; set; }
		public Nullable<int> BloodType { get; set; }

		//public virtual BloodType BloodType1 { get; set; }
		//public virtual Country Country { get; set; }

	}
}


    

PruebaCECROPIACinthya/PruebaCECROPIACinthya/Pages/About.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace PruebaCECROPIACinthya.Pages
{
    public class AboutModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your application description page.";
        }
    }
}

PruebaCECROPIACinthya/PruebaCECROPIACinthya/Pages/AllPatient.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PruebaCECROPIACinthya.Models;
using System.Collections.Generic;
using System.Linq;
using System.Configuration;
using System.Diagnostics;

namespace PruebaCECROPIACinthya.Pages
{
    public class AllPatientModel : PageModel
    {

        public List<Patient> PatientList { get; set; }

        public void OnGet()
        {
            /*var data = (from patientlist in x
                        select patientlist).ToList();*/

			PatientClient pc = new PatientClient();
			try
			{
				foreach (var x in pc.findAll())
				{
					PatientList.Add(x);
				}
			}
			catch (System.Exception e) {
				/*EventLog.WriteEntry(ConfigurationManager.AppSettings["EventLogName"].ToString()
				, e.Message);*/
			}
			

        }


        public ActionResult OnGetDelete(int? id)
        {
            if (id != null)
            {
                /*var data = (from patient in x
                            where patient.ID.Equals(id)
                            select patient).SingleOrDefault();*/

				PatientClient pc = new PatientClient();
				pc.Delete(id);
				 
            }
            return RedirectToPage("AllPatient");
        }

    }
}

PruebaCECROPIACinthya/PruebaCECROPIACinthya/Pages/Contact.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace PruebaCECROPIACinthya.Pages
{
    public class ContactModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your contact page.";
        }
    }
}

PruebaCECROPIACinthya/PruebaCECROPIACinthya/Pages/EditPatient.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PruebaCECROPIACinthya.Models;
using System.Linq;

namespace PruebaCECROPIACinthya.Pages
{
    public class EditPatientModel : PageModel
    {

        [BindProperty]
        public Patient Patient { get; set; }

        public void OnGet(int? id)
        {
            if (id != null)
            {
				PatientClient pc = new PatientClient();
				Patient = pc.findID(id);

            }
        }


        public ActionResult OnPost()
        {
            var patient = Patient;
            if (!ModelState.IsValid)
            {
                return Page();
            }

			PatientClient pc = new PatientClient();
			pc.Edit(patient);

            /*_Context.Entry(patient).Property(x => x.ID).IsModified = true;     
            _Context.SaveChanges();*/

            return RedirectToPage("AllPatient");
        }
    }
}

PruebaCECROPIACinthya/PruebaCECROPIACinthya/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace PruebaCECROPIACinthya.Pages
{
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

PruebaCECROPIACinthya/PruebaCECROPIACinthya/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace PruebaCECROPIACinthya.Pages
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

PruebaCECROPIACinthya/PruebaCECROPIACinthya/Pages/Patient.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PruebaCECROPIACinthya.Models;

namespace PruebaCECROPIACinthya.Pages
{
    public class PatientModel : PageModel
    {
		//DatabaseContext _Context;
		/*public PatientModel(DatabaseContext databasecontext)
        {
            _Context = databasecontext;
        }*/

		public PatientModel()
		{
		}

        [BindProperty]
        public Patient Patient { get; set; }

        public void OnGet()
        {

        }

		[HttpPost]
		public ActionResult OnPost()
        {
			var patient = Patient;

			if (!ModelState.IsValid) //validate the dataanotations defined for the model
			{
				return Page(); // return page
			}
	
			PatientClient pc = new PatientClient();
			pc.Create(patient);
			//  var result = _Context.Add(patient);
			//_Context.SaveChanges(); // Saving Data in database

			return RedirectToPage("AllPatient");
		}
    }
}

PruebaCECROPIACinthya/PruebaCECROPIACinthya/Pages/About.cshtml
@page
@model AboutModel
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

<p>Use this area to provide additional information.</p>

PruebaCECROPIACinthya/PruebaCECROPIACinthya/Pages/AllPatient.cshtml
@page
@using PruebaCECROPIACinthya.Models
@model AllPatientModel

<h2>Index</h2>

<p>
    <a asp-page="Patient">Create New Patient</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayName("FirstName")
            </th>
            <th>
                @Html.DisplayName("LastName")
            </th>
            <th>
                @Html.DisplayName("DateBirth")
            </th>
            <th>
                @Html.DisplayName("Nationality")
            </th>
            <th>
                @Html.DisplayName("Diseases")
            </th>
            <th>
                @Html.DisplayName("PhoneNumber")
            </th>
            <th>
                @Html.DisplayName("BloodType")
            </th>

            <th>Edit | Delete</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.PatientList)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateBirth)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nationality)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Diseases)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhoneNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BloodType)
            </td>
            <td>
                <a asp-page="./EditPatient" asp-route-id="@item.ID">Edit</a> |
                <a asp-page="./AllPatient" onclick="return confirm('Are you sure you want to delete this item?');" asp-page-handler="Delete" asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
        }
    </tbody>
</table>

PruebaCECROPIACinthya/PruebaCECROPIACinthya/Pages/Contact.cshtml
@page
@model ContactModel
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

PruebaCECROPIACinthya/PruebaCECROPIACinthya/Pages/EditPatient.cshtml
@page "{id:int}"
@using PruebaCECROPIACinthya.Models
@model EditPatientModel

<div class="container">
    <h3>Edit Patient</h3>
    <hr />
    <br />
    <form method="post">
        <input asp-for="Patient.ID" type="hidden" />
        <div class="row">
            <div class="col-md-4">
                <label asp-for="Patient.FirstName"></label>
                <input asp-for="Patient.FirstName" class="form-control" />
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <label asp-for="Patient.LastName"></label>
                <input asp-for="Patient.LastName" class="form-control" />
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <label asp-for="Patient.DateBirth"></label>
                <input asp-for="Patient.DateBirth" class="form-control" />
            </div>
        </div>

        <div class="row">
            <div class="col-md-4">
                <label asp-for="Patient.Nationality"></label>
                <input asp-for="Patient.Nationality" cl class="form-control" />
            </div>
        </div>

        <div class="row">
            <div class="col-md-4">
                <label asp-for="Patient.Diseases"></label>
                <input asp-for="Patient.Diseases" class="form-control" />
            </div>
        </div>

        <div class="row">
            <div class="col-md-4">
                <label asp-for="Patient.PhoneNumber"></label>
                <input asp-for="Patient.PhoneNumber" class="form-control" />
            </div>
        </div>

        <div class="row">
            <div class="col-md-4">
                <label asp-for="Patient.BloodType"></label>
                <input asp-for="Patient.BloodType" class="form-control" />
            </div>
        </div>

        <br />
        <input type="submit" value="Save" class="btn btn-primary" />
        <a class="btn btn-default" href="/allpatient">Cancel</a>
    </form>
</div>

PruebaCECROPIACinthya/PruebaCECROPIACinthya/Pages/Index.cshtml
@page
@model IndexModel
@{
	ViewData["Title"] = "Home page";
}

<div class="container">
	<h3>CECROPIA TEST</h3>

	<a class="btn btn-default" href="/patient">Add Patient</a>

	<a class="btn btn-default" href="/allpatient">All Patient</a>

</div>

PruebaCECROPIACinthya/PruebaCECROPIACinthya/Pages/Patient.cshtml
@page
@using PruebaCECROPIACinthya.Models @*namespace*@
@model PatientModel

<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>


<div class="container">
    <h3>Add Patient</h3>
    <hr />
    <br />
    <form method="post">
        <div class="row">
            <div class="col-md-4">
                <label asp-for="Patient.ID"></label>
                <input asp-for="Patient.ID" class="form-control" />
                <span class="alert-danger" asp-validation-for="Patient.ID"></span>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <label asp-for="Patient.FirstName"></label>
                <input asp-for="Patient.FirstName" class="form-control" />
                <span class="alert-danger" asp-validation-for="Patient.FirstName"></span>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <label asp-for="Patient.LastName"></label>
                <input asp-for="Patient.LastName" class="form-control" />
                <span class="alert-danger" asp-validation-for="Patient.LastName"></span>
            </div>
        </div>

        <div class="row">
            <div class="col-md-4">
                <label asp-for="Patient.DateBirth"></label>
                <input asp-for="Patient.DateBirth" cl class="form-control" />
                <span class="alert-danger" asp-validation-for="Patient.DateBirth"></span>
            </div>
        </div>

        <div class="row">
            <div class="col-md-4">
                <label asp-for="Patient.Nationality"></label>
                <input asp-for="Patient.Nationality" class="form-control" />
                <span class="alert-danger" asp-validation-for="Patient.Nationality"></span>
            </div>
        </div>

        <div class="row">
            <div class="col-md-4">
                <label asp-for="Patient.Diseases"></label>
                <input asp-for="Patient.Diseases" class="form-control" />
                <span class="alert-danger" asp-validation-for="Patient.Diseases"></span>
            </div>
        </div>

        <div class="row">
            <div class="col-md-4">
                <label asp-for="Patient.PhoneNumber"></label>
                <input asp-for="Patient.PhoneNumber" class="form-control" />
                <span class="alert-danger" asp-validation-for="Patient.PhoneNumber"></span>
            </div>
        </div>


        <div class="row">
            <div class="col-md-4">
                <label asp-for="Patient.BloodType"></label>
                <input asp-for="Patient.BloodType" class="form-control" />
                <span class="alert-danger" asp-validation-for="Patient.BloodType"></span>
            </div>
        </div>

        <br />
        <input type="submit" value="Save" class="btn btn-primary" />
        <a class="btn btn-default" href="/allpatient">Cancel</a>
    </form>
</div>

PruebaCECROPIACinthya/PruebaCECROPIACinthya/Pages/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PruebaCECROPIACinthya</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-page="/Index" class="navbar-brand">PruebaCECROPIACinthya</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-page="/Index">Home</a></li>
                    <li><a asp-page="/About">About</a></li>
                    <li><a asp-page="/Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - PruebaCECROPIACinthya</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>